# Site settings
title: Knight of the Old Code
email: tricorius@knightoftheoldcode.com
description: > # this means to ignore newlines until "baseurl:"
  Tricorius is the author of a few books and an incredibly popular (in his own mind) 
  developer blog. He works on mind-numbingly huge legacy applications to put steak on
  the table while his side-gigs recently added salt and pepper shakers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://knightodtheoldcode.com" # the base hostname & protocol for your site
github_username:  tricorius

# Build settings
markdown: kramdown

permalink: pretty

collections:
  books:
    output: true
    permalink: /books/:path/
    
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap